In [1]:
import numpy as np

In [21]:
with open('x','wb') as f:
    np.save(f,np.array([3,21,2]))

In [24]:
np.load('x')

array([1, 2, 3])

In [25]:
with open('x','wb') as f:
    np.save(f,np.array([1,2,3]))
    np.save(f,np.array([3,3,3,]))
    np.save(f,np.array([4,0,55]))

In [26]:
with open('x','rb') as f:
    a = np.load(f)
    b = np.load(f)
    c = np.load(f)
    


print(a,b,c)


[1 2 3] [3 3 3] [ 4  0 55]


In [11]:
np.load('x')

array([1, 2, 3])

In [28]:
x = np.arange(5)
y = np.array([3,3,3])
z = np.random.rand(5)

with open('zz','wb') as f:
    np.savez(f,arr1 = x,arr2 = y, arr3 = z)

In [41]:
npzfile = np.load('zz')
type(np.load('zz'))

numpy.lib.npyio.NpzFile

In [43]:
npzfile.files

['arr1', 'arr2', 'arr3']

In [44]:
print(npzfile['arr1'])
print(npzfile['arr2'])
print(npzfile['arr3'])

[0 1 2 3 4]
[3 3 3]
[0.93752205 0.42457251 0.12870015 0.74034324 0.5820696 ]


In [46]:
u = np.arange(1.0,5.0,1.0)
r = np.arange(10).reshape(2,5)

In [47]:
u

array([1., 2., 3., 4.])

In [48]:
r

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
np.savetxt('txt.out',[x],delimiter = ',',fmt = '%d')

In [ ]:
# %load 'txt.out'
0,1,2,3,4


In [62]:
np.savetxt('txt2.out',[x],delimiter = ',',fmt = '%f')

In [ ]:
# %load 'txt2.out'
0.000000,1.000000,2.000000,3.000000,4.000000


In [65]:
np.savetxt('txt.gz',[x],delimiter = ',')

In [71]:
#讀取gz檔案
import gzip
with gzip.open('txt.gz','r') as f:
    read = f.read()
    
read

b'0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00\n'

In [75]:
np.savetxt('txt.csv',r,delimiter = ',')

In [ ]:
# %load txt.csv
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00
