In [3]:
import numpy as np

In [2]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
sum(a)

55

In [4]:
np.sum(a)

55

In [5]:
a.sum()

55

In [39]:
b = np.arange(-6, 14, 2)
print(b)

[-6 -4 -2  0  2  4  6  8 10 12]


In [26]:
c = [ 6,-4, -2  ,0, 2 , 4 , 6 , 8 ,10, np.nan]

In [51]:
s = np.fmax(b,c)
s

array([ 6., -4., -2.,  0.,  2.,  4.,  6.,  8., 10., 12.])

In [28]:
np.nanmin(a,c)

TypeError: 'list' object cannot be interpreted as an integer

In [35]:
a = a.reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [34]:
print(a.sum(axis = 0))

[ 7  9 11 13 15]


In [36]:
print(a.sum(axis =1))

[15 40]


In [49]:
s

In [55]:
s = np.sort(s)
print(s)

[-4. -2.  0.  2.  4.  6.  6.  8. 10. 12.]


In [56]:
np.searchsorted(s,3.53)

4

In [57]:
np.searchsorted(s,3.01)

4

In [59]:
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10]


In [63]:
print(a.flat)

In [64]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
np.random.seed(0)
a = np.random.randint(-10,20,size = (5,3))

In [5]:
a

array([[  2,   5,  11],
       [-10,  -7,  17],
       [ -7,  -3,  -1],
       [  9,  11,   8],
       [ -6,  13,  -4]])

In [6]:
np.where(a < -3)

(array([1, 1, 2, 4, 4]), array([0, 1, 0, 0, 2]))

In [7]:
np.where(a >=5,'Y','N')

array([['N', 'Y', 'Y'],
       ['N', 'N', 'Y'],
       ['N', 'N', 'N'],
       ['Y', 'Y', 'Y'],
       ['N', 'Y', 'N']], dtype='<U1')

In [8]:
np.nonzero(a)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [9]:
np.sort(a)

array([[  2,   5,  11],
       [-10,  -7,  17],
       [ -7,  -3,  -1],
       [  8,   9,  11],
       [ -6,  -4,  13]])

In [10]:
a


array([[  2,   5,  11],
       [-10,  -7,  17],
       [ -7,  -3,  -1],
       [  9,  11,   8],
       [ -6,  13,  -4]])

In [11]:
np.sort(a, axis =1)

array([[  2,   5,  11],
       [-10,  -7,  17],
       [ -7,  -3,  -1],
       [  8,   9,  11],
       [ -6,  -4,  13]])

In [12]:
np.sort(a, axis =0)

array([[-10,  -7,  -4],
       [ -7,  -3,  -1],
       [ -6,   5,   8],
       [  2,  11,  11],
       [  9,  13,  17]])

In [13]:
np.argsort(a)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [0, 2, 1]])

In [14]:
a.sort()

In [15]:
a


array([[  2,   5,  11],
       [-10,  -7,  17],
       [ -7,  -3,  -1],
       [  8,   9,  11],
       [ -6,  -4,  13]])

In [17]:
b = np.random.randint(0,20,size = (5,2))
b

array([[12,  1],
       [ 6,  7],
       [14, 17],
       [ 5, 13],
       [ 8,  9]])

In [18]:
c = np.random.randint(5,15, size = (3,3))
c

array([[ 9,  8,  5],
       [ 8, 10,  5],
       [ 7,  8, 13]])

In [33]:
d = np.random.randint(-3,8, size = (5,3))
d

array([[-1, -3,  0],
       [ 2,  6,  7],
       [ 1,  1,  3],
       [ 1,  1,  0],
       [ 1,  1,  5]])

In [30]:
np.concatenate((a,b), axis = 1) 

array([[  2,   5,  11,  12,   1],
       [-10,  -7,  17,   6,   7],
       [ -7,  -3,  -1,  14,  17],
       [  8,   9,  11,   5,  13],
       [ -6,  -4,  13,   8,   9]])

In [34]:
np.stack((a,d))

array([[[  2,   5,  11],
        [-10,  -7,  17],
        [ -7,  -3,  -1],
        [  8,   9,  11],
        [ -6,  -4,  13]],

       [[ -1,  -3,   0],
        [  2,   6,   7],
        [  1,   1,   3],
        [  1,   1,   0],
        [  1,   1,   5]]])

In [35]:
np.hstack((a,b))

array([[  2,   5,  11,  12,   1],
       [-10,  -7,  17,   6,   7],
       [ -7,  -3,  -1,  14,  17],
       [  8,   9,  11,   5,  13],
       [ -6,  -4,  13,   8,   9]])

In [37]:
np.vstack((a,c))

array([[  2,   5,  11],
       [-10,  -7,  17],
       [ -7,  -3,  -1],
       [  8,   9,  11],
       [ -6,  -4,  13],
       [  9,   8,   5],
       [  8,  10,   5],
       [  7,   8,  13]])

In [39]:
np.split(a,5)

[array([[ 2,  5, 11]]),
 array([[-10,  -7,  17]]),
 array([[-7, -3, -1]]),
 array([[ 8,  9, 11]]),
 array([[-6, -4, 13]])]

In [40]:
np.split(a, [5,3])

[array([[  2,   5,  11],
        [-10,  -7,  17],
        [ -7,  -3,  -1],
        [  8,   9,  11],
        [ -6,  -4,  13]]),
 array([], shape=(0, 3), dtype=int64),
 array([[ 8,  9, 11],
        [-6, -4, 13]])]

In [41]:
np.split(b, [5,2])

[array([[12,  1],
        [ 6,  7],
        [14, 17],
        [ 5, 13],
        [ 8,  9]]), array([], shape=(0, 2), dtype=int64), array([[14, 17],
        [ 5, 13],
        [ 8,  9]])]

In [43]:
e = np.random.randint(0,20, size = (6,8))
e

array([[16,  0,  0,  6, 19, 14, 10, 19],
       [ 8, 13,  2,  3,  2, 11, 13, 16],
       [ 8,  8, 19,  8,  2,  3, 12, 14],
       [ 0,  4,  3, 13, 11, 13, 13, 11],
       [16, 14, 16, 19,  1,  8,  0,  4],
       [ 6, 13,  7, 15,  9, 18,  8, 15]])

In [44]:
np.split(e, [3,4])

[array([[16,  0,  0,  6, 19, 14, 10, 19],
        [ 8, 13,  2,  3,  2, 11, 13, 16],
        [ 8,  8, 19,  8,  2,  3, 12, 14]]),
 array([[ 0,  4,  3, 13, 11, 13, 13, 11]]),
 array([[16, 14, 16, 19,  1,  8,  0,  4],
        [ 6, 13,  7, 15,  9, 18,  8, 15]])]

In [45]:
np.split(e, [2,4,5])

[array([[16,  0,  0,  6, 19, 14, 10, 19],
        [ 8, 13,  2,  3,  2, 11, 13, 16]]),
 array([[ 8,  8, 19,  8,  2,  3, 12, 14],
        [ 0,  4,  3, 13, 11, 13, 13, 11]]),
 array([[16, 14, 16, 19,  1,  8,  0,  4]]),
 array([[ 6, 13,  7, 15,  9, 18,  8, 15]])]

In [47]:
np.split(e, [3,6], axis = 1)

[array([[16,  0,  0],
        [ 8, 13,  2],
        [ 8,  8, 19],
        [ 0,  4,  3],
        [16, 14, 16],
        [ 6, 13,  7]]), array([[ 6, 19, 14],
        [ 3,  2, 11],
        [ 8,  2,  3],
        [13, 11, 13],
        [19,  1,  8],
        [15,  9, 18]]), array([[10, 19],
        [13, 16],
        [12, 14],
        [13, 11],
        [ 0,  4],
        [ 8, 15]])]

In [48]:
np.hsplit(e, [3,6])np.hsplit(e, [3,6])

[array([[16,  0,  0],
        [ 8, 13,  2],
        [ 8,  8, 19],
        [ 0,  4,  3],
        [16, 14, 16],
        [ 6, 13,  7]]), array([[ 6, 19, 14],
        [ 3,  2, 11],
        [ 8,  2,  3],
        [13, 11, 13],
        [19,  1,  8],
        [15,  9, 18]]), array([[10, 19],
        [13, 16],
        [12, 14],
        [13, 11],
        [ 0,  4],
        [ 8, 15]])]

In [49]:
np.vsplit(e, [3,6])

[array([[16,  0,  0,  6, 19, 14, 10, 19],
        [ 8, 13,  2,  3,  2, 11, 13, 16],
        [ 8,  8, 19,  8,  2,  3, 12, 14]]),
 array([[ 0,  4,  3, 13, 11, 13, 13, 11],
        [16, 14, 16, 19,  1,  8,  0,  4],
        [ 6, 13,  7, 15,  9, 18,  8, 15]]),
 array([], shape=(0, 8), dtype=int64)]

In [50]:
np.sum(a)

38

In [51]:
a.sum()

38

In [52]:
sum(a)

array([-13,   0,  51])