In [2]:
import numpy as np
a = np.array([20,30, 40, 50])
b = np.arange(4)

print(a > b)

[ True  True  True  True]


In [3]:
print(b)

[0 1 2 3]


In [4]:
print(a <b)
print(a == b)
print(a != b)

[False False False False]
[False False False False]
[ True  True  True  True]


In [5]:
c = np.array([True, True, True, True])
d = np.array([False, False, True, False])

print(c and d)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [7]:
print(c | d)

[ True  True  True  True]


In [9]:
print( c & d)

[False False  True False]


In [10]:
#遮罩
print(a[c])

[20 30 40 50]


In [14]:
#遮罩
print(a[d])

[40]


In [15]:
print(a > 30)

[False False  True  True]


In [16]:
print(a[a>20])

[30 40 50]


In [18]:
w = np.arange(100)
v = []
for i in w:
    if i >= 69:
        v.append(i)
print(v)

[69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [19]:
h =[]
for i in w:
    if i % 2 == 0:
        h.append(i)

print(h)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [20]:
y = w[ w % 2 == 0]
print(y)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
