In [6]:
import numpy as np
np.random.seed(1)

In [7]:
a = np.random.randint(1,10,6).reshape(2,3)

In [8]:
a

array([[6, 9, 6],
       [1, 1, 2]])

In [9]:
b = np.random.randint(1,20,3)

In [10]:
b

array([13,  8, 14])

In [13]:
np.maximum(a,b)


array([[13,  9, 14],
       [13,  8, 14]])

In [14]:
np.minimum(a,b)

array([[6, 8, 6],
       [1, 1, 2]])

In [15]:
c = [(0,np.nan,np.nan)]

In [16]:
np.maximum(a,c)

array([[ 6., nan, nan],
       [ 1., nan, nan]])

In [17]:
np.minimum(a,c)

array([[ 0., nan, nan],
       [ 0., nan, nan]])

In [18]:
np.fmax(a,b)

array([[13,  9, 14],
       [13,  8, 14]])

In [19]:
np.fmax(a,c)

array([[6., 9., 6.],
       [1., 1., 2.]])

In [20]:
np.fmin(a,c)

array([[0., 9., 6.],
       [0., 1., 2.]])

In [21]:
np.nanmax(a)

9

In [22]:
np.nanmin(a)

1

In [30]:
np.nanmax(a,axis = 0,keepdims = 1)

array([[6, 9, 6]])

In [31]:
v = ([2,7,4],[1,9,3])

In [32]:
np.nanmax(v, axis = 0)

array([2, 9, 4])

In [33]:
np.nanmax(v, axis = 1)

array([7, 9])

In [34]:
np.nanmin(v, axis = 1)

array([2, 1])

In [35]:
f = ([np.nan,5,0],[-5,np.nan,np.nan])

In [36]:
np.nanmax(f, axis = 0)

array([-5.,  5.,  0.])

In [37]:
np.nanmax(f, axis = 1)

array([ 5., -5.])

In [38]:
s = ([np.nan,5,0],[np.nan,np.nan,np.nan])

In [39]:
np.nanmax(s , axis = 1)

/Users/ging/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: All-NaN axis encountered
  """Entry point for launching an IPython kernel.


array([ 5., nan])

In [56]:
a = np.arange(1,10).astype('float64')
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
np.percentile(a,50)

5.0

In [57]:
print(a.dtype)

float64


In [60]:
a[4] = np.nan
a

array([ 1.,  2.,  3.,  4., nan,  6.,  7.,  8.,  9.])

In [61]:
np.percentile(a,40)

nan

In [62]:
np.nanpercentile(a,40)

3.8000000000000003