In [2]:
import numpy as np

In [16]:
a = np.array([[1,3,5],[2,4,6]])
d = np.array([[1,3,5],[2,4,6]])

In [4]:
a

array([[1, 3, 5],
       [2, 4, 6]])

In [10]:
b = a.flatten()
b

array([1, 3, 5, 2, 4, 6])

In [17]:
c = d.ravel()
c

array([1, 3, 5, 2, 4, 6])

In [20]:
b[1] = 9
b,a

(array([1, 9, 5, 2, 4, 6]),
 array([[1, 3, 5],
        [2, 4, 6]]))

In [21]:
c[1] = 9
c,d

(array([1, 9, 5, 2, 4, 6]),
 array([[1, 9, 5],
        [2, 4, 6]]))

In [25]:
b = a.flatten(order = 'C')
b

array([1, 3, 5, 2, 4, 6])

In [26]:
b = a.flatten(order = 'F')
b

array([1, 2, 3, 4, 5, 6])

In [27]:
c = d.flatten(order = 'C')
c

array([1, 9, 5, 2, 4, 6])

In [28]:
c = d.flatten(order = 'F')
c

array([1, 2, 9, 4, 5, 6])

In [29]:
b = a.ravel(order = 'F')
b

array([1, 2, 3, 4, 5, 6])

In [31]:
b = d.ravel(order = 'C')
b

array([1, 9, 5, 2, 4, 6])

In [32]:
a = np.arange(15)

In [33]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
b = a.reshape(3,-1)

In [35]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
b[1,2] = 50
b


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 50,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
a

array([ 0,  1,  2,  3,  4,  5,  6, 50,  8,  9, 10, 11, 12, 13, 14])

In [40]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
a = np.array([[[1,2],[1,2],[1,2]],[[4,5],[4,5],[4,5]]])
a

array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[4, 5],
        [4, 5],
        [4, 5]]])

In [46]:
a.shape

(2, 3, 2)

In [47]:
a.sum(axis= 0)

array([[5, 7],
       [5, 7],
       [5, 7]])

In [48]:
a.sum(axis = 1)

array([[ 3,  6],
       [12, 15]])

In [49]:
a.sum(axis = 2)

array([[3, 3, 3],
       [9, 9, 9]])

In [50]:
a

array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[4, 5],
        [4, 5],
        [4, 5]]])

In [51]:
a.reshape(1,-1)

array([[1, 2, 1, 2, 1, 2, 4, 5, 4, 5, 4, 5]])

In [59]:
a.reshape(1,-1).shape


(1, 12)

In [62]:
a[:,np.newaxis,:].shape

(2, 1, 3, 2)

In [61]:
a

array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[4, 5],
        [4, 5],
        [4, 5]]])

In [63]:
a[:,np.newaxis,:]

array([[[[1, 2],
         [1, 2],
         [1, 2]]],


       [[[4, 5],
         [4, 5],
         [4, 5]]]])

In [65]:
a= np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
b = np.array([[1,1,1],[1,1,1]])
b

array([[1, 1, 1],
       [1, 1, 1]])

In [67]:
np.concatenate((a,b))

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
np.stack((a,b))

array([[[0, 1, 2],
        [3, 4, 5]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [69]:
np.stack((a,b),axis = 1)

array([[[0, 1, 2],
        [1, 1, 1]],

       [[3, 4, 5],
        [1, 1, 1]]])

In [70]:
np.stack((a,b),axis = 2)

array([[[0, 1],
        [1, 1],
        [2, 1]],

       [[3, 1],
        [4, 1],
        [5, 1]]])

In [71]:
np.hstack((a,b))

array([[0, 1, 2, 1, 1, 1],
       [3, 4, 5, 1, 1, 1]])

In [72]:
np.vstack((a,b))

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 1],
       [1, 1, 1]])

In [73]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
np.split(a,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [77]:
np.split(a,[3,2])

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [78]:
np.split(a,[3,1])

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([], shape=(0, 3), dtype=int64),
 array([[3, 4, 5]])]

In [79]:
np.split(a,[2,3])

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [81]:
np.hsplit(a,[1,2])

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [88]:
for i in a:
 print (i)

[0 1 2]
[3 4 5]


In [89]:
for i in a.flat:
    print(i)

0
1
2
3
4
5


In [93]:
a = np.random.randint(1,10,6)
a


array([3, 8, 3, 4, 7, 4])

In [95]:
a.min()

3

In [96]:
a.max()

8

In [97]:
np.amin(a)

3

In [98]:
np.amax(a)

8

In [104]:
b = a.reshape(2,3)
b

array([[3, 8, 3],
       [4, 7, 4]])

In [103]:
b.min(axis = 0)

array([3, 7, 3])

In [105]:
b.min(axis = 1)

array([3, 4])

In [106]:
b.argmin()

0

In [107]:
b.argmin(axis = 1)

array([0, 0])

In [108]:
b.argmax(axis = 0)

array([1, 0, 1])

In [109]:
np.where(b>5)

(array([0, 1]), array([1, 1]))

In [110]:
np.where(b>5,"Y","N")

array([['N', 'Y', 'N'],
       ['N', 'Y', 'N']], dtype='<U1')

In [112]:
q = np.random.randint(0,5,6)
q

array([3, 1, 2, 3, 1, 0])

In [113]:
q.nonzero()

(array([0, 1, 2, 3, 4]),)

In [22]:
import numpy as np
z = np.random.randint(-500000,500000,10000)
z


array([ 169987,  248150,  161587, ..., -173296,   10047, -465110])

In [23]:
np.sort(z)

array([-499923, -499676, -499599, ...,  499854,  499875,  499991])

In [24]:
np.sort(z, kind = 'heapsort')

array([-499923, -499676, -499599, ...,  499854,  499875,  499991])

In [17]:
z

array([  87, -248,  470,  222,  472,  435,  424, -280,  431,   63, -108,
        301, -263,  357,  -82, -255,  465, -415, -104,  403,  164, -156,
       -297,   89,  413,  310,  167,  150,   92,  307,  -64, -312,  380,
       -310, -390,  -73, -118, -329, -284,  307,  266, -328, -292, -152,
        -91,  117,  222,  303, -236,  253,  -69,  348, -488, -177, -269,
        198, -355, -306,  185,  348, -478,  192,  180,  265,  187,  174,
       -257,  342,   -7, -394, -298,   23,  -81,  378,  -67,  338,  -63,
       -410, -194,  462,  267,  -83, -376,  121,  263,  -77, -271,   86,
       -408,  -83, -290, -318,  238, -404,  499, -285, -391, -107, -104,
        368])

In [20]:
z.sort()
z

array([-488, -478, -415, -410, -408, -404, -394, -391, -390, -376, -355,
       -329, -328, -318, -312, -310, -306, -298, -297, -292, -290, -285,
       -284, -280, -271, -269, -263, -257, -255, -248, -236, -194, -177,
       -156, -152, -118, -108, -107, -104, -104,  -91,  -83,  -83,  -82,
        -81,  -77,  -73,  -69,  -67,  -64,  -63,   -7,   23,   63,   86,
         87,   89,   92,  117,  121,  150,  164,  167,  174,  180,  185,
        187,  192,  198,  222,  222,  238,  253,  263,  265,  266,  267,
        301,  303,  307,  307,  310,  338,  342,  348,  348,  357,  368,
        378,  380,  403,  413,  424,  431,  435,  462,  465,  470,  472,
        499])

In [21]:
z


array([-488, -478, -415, -410, -408, -404, -394, -391, -390, -376, -355,
       -329, -328, -318, -312, -310, -306, -298, -297, -292, -290, -285,
       -284, -280, -271, -269, -263, -257, -255, -248, -236, -194, -177,
       -156, -152, -118, -108, -107, -104, -104,  -91,  -83,  -83,  -82,
        -81,  -77,  -73,  -69,  -67,  -64,  -63,   -7,   23,   63,   86,
         87,   89,   92,  117,  121,  150,  164,  167,  174,  180,  185,
        187,  192,  198,  222,  222,  238,  253,  263,  265,  266,  267,
        301,  303,  307,  307,  310,  338,  342,  348,  348,  357,  368,
        378,  380,  403,  413,  424,  431,  435,  462,  465,  470,  472,
        499])

In [28]:
v = np.random.randint(0,36,size = (2,6,2))
v

array([[[19,  9],
        [ 9, 10],
        [34, 29],
        [11, 23],
        [25, 15],
        [27,  1]],

       [[ 1,  7],
        [12,  3],
        [34, 17],
        [12, 19],
        [14, 26],
        [ 3, 28]]])

In [29]:
np.sort(v,axis = 0)

array([[[ 1,  7],
        [ 9,  3],
        [34, 17],
        [11, 19],
        [14, 15],
        [ 3,  1]],

       [[19,  9],
        [12, 10],
        [34, 29],
        [12, 23],
        [25, 26],
        [27, 28]]])

In [30]:
np.sort(v,axis = 1)

array([[[ 9,  1],
        [11,  9],
        [19, 10],
        [25, 15],
        [27, 23],
        [34, 29]],

       [[ 1,  3],
        [ 3,  7],
        [12, 17],
        [12, 19],
        [14, 26],
        [34, 28]]])

In [31]:
np.sort(v,axis = 2)

array([[[ 9, 19],
        [ 9, 10],
        [29, 34],
        [11, 23],
        [15, 25],
        [ 1, 27]],

       [[ 1,  7],
        [ 3, 12],
        [17, 34],
        [12, 19],
        [14, 26],
        [ 3, 28]]])