In [2]:
import numpy as np

In [10]:
a = np.random.randint(0,10,10).reshape(2,5)
a

array([[3, 0, 1, 9, 5],
       [2, 5, 6, 6, 4]])

In [11]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [12]:
a + b

array([[ 3,  1,  3, 12,  9],
       [ 2,  6,  8,  9,  8]])

In [13]:
np.add(a,b)

array([[ 3,  1,  3, 12,  9],
       [ 2,  6,  8,  9,  8]])

In [14]:
a - b

array([[ 3, -1, -1,  6,  1],
       [ 2,  4,  4,  3,  0]])

In [17]:
np.multiply(a,b)

array([[ 0,  0,  2, 27, 20],
       [ 0,  5, 12, 18, 16]])

In [18]:
a.sum()

41

In [19]:
np.sum(a)

41

In [20]:
a.sum(axis = 0)

array([ 5,  5,  7, 15,  9])

In [21]:
np.sum(a, axis = 0)

array([ 5,  5,  7, 15,  9])

In [22]:
a.sum(axis = 1)

array([18, 23])

In [24]:
np.power(a,b)

array([[  1,   0,   1, 729, 625],
       [  1,   5,  36, 216, 256]])

In [26]:
a**b

array([[  1,   0,   1, 729, 625],
       [  1,   5,  36, 216, 256]])

In [28]:
np.sqrt(a)

array([[1.73205081, 0.        , 1.        , 3.        , 2.23606798],
       [1.41421356, 2.23606798, 2.44948974, 2.44948974, 2.        ]])

In [29]:
np.e

2.718281828459045

In [31]:
np.exp(1)

2.718281828459045

In [32]:
np.exp(0)

1.0

In [33]:
np.exp(4)

54.598150033144236

In [34]:
np.exp(np.arange(3))

array([1.        , 2.71828183, 7.3890561 ])

In [36]:
np.log(np.e)

1.0

In [38]:
np.log2(32)

5.0

In [39]:
np.log(49)/np.log(7)

2.0

In [40]:
np.log(a)

<ipython-input-40-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([[1.09861229,       -inf, 0.        , 2.19722458, 1.60943791],
       [0.69314718, 1.60943791, 1.79175947, 1.79175947, 1.38629436]])

In [42]:
np.round(0.645,2)

0.64

In [43]:
0.3+0.3+0.3==0.9

False

In [44]:
3*0.1

0.30000000000000004

In [45]:
np.round(0.1+0.1+0.1,1) == np.round(0.3,1)

True

In [46]:
from decimal import Decimal

In [48]:
f = Decimal('0.1')

In [49]:
g = Decimal('0.3')

In [50]:
f + f+ f == g 

True

In [52]:
a = np.array([1.35,3.08,2.68,-4.45])
a

array([ 1.35,  3.08,  2.68, -4.45])

In [53]:
np.round(a,1)

array([ 1.4,  3.1,  2.7, -4.4])

In [54]:
np.round(a,0)

array([ 1.,  3.,  3., -4.])

In [55]:
np.rint(a)

array([ 1.,  3.,  3., -4.])

In [56]:
np.trunc(a)

array([ 1.,  3.,  2., -4.])

In [57]:
np.floor(a)

array([ 1.,  3.,  2., -5.])

In [59]:
np.ceil(a)

array([ 2.,  4.,  3., -4.])

In [60]:
np.fix(a)

array([ 1.,  3.,  2., -4.])

In [2]:
import numpy as np
a = np.array([1.35,3.08,2.68,-4.45])
np.abs(a)

array([1.35, 3.08, 2.68, 4.45])

In [4]:
np.fabs(a)

array([1.35, 3.08, 2.68, 4.45])

In [5]:
b = 2+2j
np.fabs(b)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''