In [1]:
import numpy as np
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
a[3]

3

In [4]:
a[2:3]

array([2])

In [5]:
b = np.arange(3) ** 3
b

array([0, 1, 8])

In [6]:
b[-1] #提出最後一個值

8

In [7]:
for i in b:
    print(i)
    


0
1
8


In [8]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
c[0]

array([0, 1, 2])

In [10]:
c[1]

array([3, 4, 5])

In [11]:
c[0:1]

array([[0, 1, 2]])

In [12]:
c[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
c[:,0:2] 

array([[0, 1],
       [3, 4]])

In [14]:
c[1,2]

5

In [15]:
c[:,1:3]

array([[1, 2],
       [4, 5]])

In [16]:
for i in c:
    print(i)

[0 1 2]
[3 4 5]


In [17]:
for row in c:
    for i in row:
        print(i)

0
1
2
3
4
5


In [18]:
for i in c.flat:
    print(i)

0
1
2
3
4
5


In [19]:
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5


In [20]:
%timeit np.nditer(c)

768 ns ± 183 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [21]:
%timeit c.flat

189 ns ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
%%time
for row in c:
    for i in row:
        print(i)

0
1
2
3
4
5
CPU times: user 251 µs, sys: 16 µs, total: 267 µs
Wall time: 273 µs


In [23]:
%%time
for i in c.flat:
    print(i)

0
1
2
3
4
5
CPU times: user 206 µs, sys: 15 µs, total: 221 µs
Wall time: 227 µs


In [24]:
%%time 
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5
CPU times: user 264 µs, sys: 10 µs, total: 274 µs
Wall time: 281 µs


In [25]:
for i in np.nditer(c, order ='C'):
    print(i)

0
1
2
3
4
5


In [26]:
for i in np.nditer(c, order = 'F'):
    print(i)

0
3
1
4
2
5


In [2]:
import numpy as np
np.random.seed(3)
A = np.arange(6).reshape(2,3)
B = np.arange(12).reshape(3,4)
print(A)
print('-----')
print(B)

[[0 1 2]
 [3 4 5]]
-----
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
print(A.dot(B))

[[20 23 26 29]
 [56 68 80 92]]


In [29]:
np.inner(A,B)

ValueError: shapes (2,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [3]:
C = np.arange(6,12).reshape(2,3)
C

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.inner(A,C)

In [4]:
D = np.arange(9).reshape(3,3)

In [ ]:
np.inner(A,D)

In [ ]:
np.outer(A,D)

In [ ]:
A.dot(3)

In [ ]:
A.matmul(3)

In [ ]:
np.matmul(A,B)

In [ ]:
A @ B

In [ ]:
A @ 2

In [31]:
np.trace(C)

16

In [5]:
V = np.arange(9).reshape(3,3)
print(V)
np.linalg.det(V)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


0.0

In [37]:
V
np.linalg.inv(V)

LinAlgError: Singular matrix

In [50]:
import random
U = np.random.randint(0,10,9).reshape(3,3)
print(U)
np.linalg.inv(U)

[[2 4 5]
 [8 8 7]
 [5 1 1]]


array([[-0.02, -0.02,  0.24],
       [-0.54,  0.46, -0.52],
       [ 0.64, -0.36,  0.32]])

In [7]:
np.transpose(V)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
np.linalg.eig(B)

LinAlgError: Last 2 dimensions of the array must be square

In [14]:
%%time
np.linalg.eig(V)

CPU times: user 180 µs, sys: 20 µs, total: 200 µs
Wall time: 192 µs


(array([ 1.33484692e+01, -1.34846923e+00, -1.15433316e-15]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

In [13]:
%%time
np.linalg.matrix_rank(B)

CPU times: user 212 µs, sys: 29 µs, total: 241 µs
Wall time: 223 µs


2

In [15]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [17]:
np.eye(3,6,5)

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
A = np.array([[3, 4, 0], [4, 4, 6], [0, 6, 5]])
A


array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

In [19]:
np.diagonal(A, offset=1)

array([4, 6])