In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
b = np.array((1,2,3,4,5))

In [6]:
b

array([1, 2, 3, 4, 5])

In [7]:
print (b)

[1 2 3 4 5]


In [8]:
type(a),type(b)

(numpy.ndarray, numpy.ndarray)

In [9]:
np.arrange(0,5,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [10]:
np.arange(0,5,2)

array([0, 2, 4])

In [11]:
np.arange(0,10,2,dtype='int64')

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0,10,0.5,dtype='int8')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [14]:
np.arange(0,10,0.5,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int16)

In [15]:
np.arange(0,10,0.5,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

沒有包含結束值： [0.13 0.14 0.15]
包含結束值： [0.12 0.13 0.14 0.15 0.16]
沒有包含結束值： [0.13 0.14 0.15]
沒有包含結束值： [0.13 0.14 0.15]


In [20]:
a = np.arange(0.13, 0.16, step=0.01)
print("沒有包含結束值：", a)
b = np.linspace(0.12, 0.16, 0.01,dtype='float64')
print("包含結束值：", b)

c = np.arange(0.13, 0.16, step=0.01)
print("沒有包含結束值：", c)
d = np.linspace(0.13, 0.16, 0.01, dtype='float64')
print("沒有包含結束值：", d)

沒有包含結束值： [0.13 0.14 0.15]


TypeError: 'float' object cannot be interpreted as an integer

In [22]:
a = np.arange(0.13, 0.16, step=0.01)
print("沒有包含結束值：", a)
b = np.linspace(0.12, 0.16, num = 0.02, endpoint = 'true')
print("包含結束值：", b)

c = np.arange(0.13, 0.16, step=0.01)
print("沒有包含結束值：", c)
d = np.linspace(0.13, 0.16,num = 0.02, endpoint = 'true')
print("沒有包含結束值：", d)

沒有包含結束值： [0.13 0.14 0.15]


TypeError: 'float' object cannot be interpreted as an integer

In [23]:
d = np.linspace(0.13, 0.16,num = 2, endpoint = 'true')

In [24]:
d = np.linspace(0.13, 0.16,num = 2, endpoint = 'true')
print(d)

[0.13 0.16]


In [25]:
d = np.linspace(0.13, 0.16,num = 10, endpoint = 'true')
print(d)

[0.13       0.13333333 0.13666667 0.14       0.14333333 0.14666667
 0.15       0.15333333 0.15666667 0.16      ]


In [26]:
d = np.linspace(0, 6,num = 3, endpoint = 'true')
print(d)

[0. 3. 6.]


In [28]:
d = np.linspace(0, 6,num = 7, endpoint = 'true')
print(d)

[0. 1. 2. 3. 4. 5. 6.]


In [1]:
a = np.array([[1,2],[1,2]])

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a= np.array([[1,2],[1,2]])

In [4]:
print(a)

[[1 2]
 [1 2]]


In [7]:
b = np.array([[[1,2],[1,2]],[[1,2],[1,2]],[[1,2],[1,2]]])

In [8]:
print(b)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [9]:
shape(b)

NameError: name 'shape' is not defined

In [10]:
b.shape

(3, 2, 2)

In [14]:
c = np.array([[[1,2,3],[1,2,3]],[[2,4,5],[2,4,5]]])

In [15]:
c.shape

(2, 2, 3)

In [16]:
print(c,b,a)

[[[1 2 3]
  [1 2 3]]

 [[2 4 5]
  [2 4 5]]] [[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]

 [[1 2]
  [1 2]]] [[1 2]
 [1 2]]


In [19]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.empty((2,4))

array([[ 1.49166815e-154, -3.11108047e+231,  1.97626258e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  1.49166815e-154,
         5.60599807e-309]])

In [22]:
np.random.seed(2)

In [23]:
np.random.rand(2,3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

In [24]:
np.random.rand(2,3)

array([[0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209]])

In [27]:
np.random.choice(10,9)
print (np.random.rand(2,3))

np.random.seed(2)
print (np.random.rand(2,3))

[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]]
[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]]


In [35]:
print (np.random.randint(2,3,4))

[2 2 2 2]


In [36]:
np.random.choice(10,9)

array([3, 5, 8, 4, 6, 3, 9, 2, 0])

In [42]:
np.random.seed(2)
print(np.random.choice(10,9))
np.random.seed(2)
print(np.random.choice(10,9))


[8 8 6 2 8 7 2 1 5]
[8 8 6 2 8 7 2 1 5]


In [44]:
np.random.choice(5,10)

array([2, 1, 2, 4, 3, 0, 4, 3, 1, 2])

In [45]:
a,b = 1,2
print(a,b)

1 2


In [46]:
print(a)

1


In [47]:
import numpy as np

In [48]:
a = np.array([[1,3,5],[2,4,6]])

In [49]:
a[1,1]

4

In [50]:
a[1,0]

2

In [51]:
a[2,1]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [53]:
a[1:2,1:2]

array([[4]])

In [54]:
a.ndim

2

In [55]:
a.dtype

dtype('int64')

In [56]:
a.size

6

In [57]:
a.flat

In [58]:
a.T

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
a.ndim

2

In [60]:
a

array([[1, 3, 5],
       [2, 4, 6]])

In [61]:
a=a.T

In [62]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
a.ndim

2

In [64]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
a.dtype

dtype('int64')

In [66]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [67]:
a.real

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
a.imag

array([[0, 0],
       [0, 0],
       [0, 0]])

In [69]:
a.date

AttributeError: 'numpy.ndarray' object has no attribute 'date'

In [70]:
a.data

In [71]:
a.itemsize

8

In [72]:
a.nbytes

48