# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [2]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [3]:
%timeit -n 10 a = 2

for v in Z:
    for row in v:
        for i in row:
            i = i+1


38.9 ns ± 19.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit -n 10 a = 2

for i in Z.flat:
    i = i+1


41.9 ns ± 17.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit -n 10 a = 2

for i in np.nditer(Z):
    i =i+1
    

43.8 ns ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [6]:

Z = np.random.randint(0,10,50)
print(Z)


[5 9 9 4 3 9 1 6 2 5 6 7 3 2 5 9 2 7 2 9 2 8 8 3 7 1 4 8 0 3 1 6 7 9 7 6 6
 2 6 1 3 8 5 2 6 4 7 0 0 8]


In [7]:
V = {}
for i in Z:
    if i not in V:
        V[i] = 1
    else:
        V[i] = V[i] +1
V
#2出現最多次

{5: 4, 9: 6, 4: 3, 3: 5, 1: 4, 6: 7, 2: 7, 7: 6, 8: 5, 0: 3}

In [8]:
np.where(Z == 2)

(array([ 8, 13, 16, 18, 20, 37, 43]),)

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [9]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[9, 8, 3, 1, 1, 4]
[9, 8, 3, 1, 1, 4]
[[6, 5, 5, 0], [2, 8, 7, 0], [3, 7, 6, 6]]
[array([6, 5, 5, 0]), array([2, 8, 7, 0]), array([3, 7, 6, 6])]
[[[2, 5], [0, 9], [5, 2]], [[0, 9], [3, 1], [0, 3]]]
[array([[2, 5],
       [0, 9],
       [5, 2]]), array([[0, 9],
       [3, 1],
       [0, 3]])]


In [10]:
print(list(b.flat))
print(list(c.flat))

[6, 5, 5, 0, 2, 8, 7, 0, 3, 7, 6, 6]
[2, 5, 0, 9, 5, 2, 0, 9, 3, 1, 0, 3]


作業目標
活用矩陣運算，實做線性代數
作業重點
線性代數公式應用
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:
array1 = np.array([[10, 8], [3, 5]])

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?

In [11]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1) @ array1
array2

#是單位矩陣

array([[1., 0.],
       [0., 1.]])

In [12]:
#2. 運用上列array計算特徵值、特徵向量?
np.linalg.eig(array1)

(array([13.,  2.]), array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [13]:
#3. 運用上列array計算SVD?
np.linalg.matrix_rank(array1)

2